name: Publish Prerequisites Images

on:
  push:
    branches: [ main ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: [ frontend, backend, tests ]
        include:
          - folder: frontend
            image: jasminegraph-ui-frontend-prerequisites
          - folder: backend
            image: jasminegraph-ui-backend-prerequisites
          - folder: tests
            image: jasminegraph-ui-tests-prerequisites

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and flatten Docker image
        run: |
          docker build -t ${{ matrix.image }}:temp ./${{ matrix.folder }}
          CONTAINER_ID=$(docker create ${{ matrix.image }}:temp)
          docker export $CONTAINER_ID | docker import - ${{ matrix.image }}:latest

      - name: Push Docker image
        run: |
          docker tag ${{ matrix.image }}:latest $DOCKER_USERNAME/${{ matrix.image }}:latest
          docker push $DOCKER_USERNAME/${{ matrix.image }}:latest
